site_name: ThymeSave Cookbook
site_description: Documentation around ThymeSave
site_author: ThymeSave Team and Community
copyright: '&copy; ThymeSave Team and Community'
use_directory_urls: false

docs_dir: docs

repo_url: https://github.com/thymesave/cookbook
repo_name: thymesave/cookbook
edit_uri: edit/main/docs/

theme:
  font: false
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.expand

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - attr_list

plugins:
  - search

extra_css:
  - assets/stylesheets/extra.css
